name: ACDC
on:
  push:
    branches: [master]
jobs:
  test-and-cover-pack:
    runs-on: ubuntu-latest
    env:
      COVERAGE_HTML_REPORT_PATH: /tmp/coverage_html_report
      COVERAGE_XML_REPORT_PATH: /tmp/coverage_html_report.xml
      PYTEST_REPORT_PATH: /tmp/pytest_report.html
    steps:
      - name: "Check repo"
        uses: actions/checkout@v3
      - name: "Python install"
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: "Requiremets install"
        run: pip install -r requirements.txt
      - name: "Some tests"
        run: coverage run -m pytest --html=${{ env.PYTEST_REPORT_PATH }} --self-contained-html
      - name: "Cover html"
        run: coverage html --directory ${{ env.COVERAGE_HTML_REPORT_PATH }}
      - name: "Archive reports for tests"
        uses: actions/upload-artifact@v3
        if: ${{!cancelled()}}
        with:
          name: "Reports!"
          path:
            ${{ env.PYTEST_REPORT_PATH }}
            ${{ env.COVERAGE_HTML_REPORT_PATH }}
      - name: "XML les goo"
        run: coverage xml -o ${{ env.COVERAGE_XML_REPORT_PATH }}
      - name: "XML to Codacy"
        uses: codacy/codacy-coverage-reporter-action@v1
        if: ${{!cancelled()}}
        with:
          project-token: ${{ secrets.CODACY_PROJECT_API_TOKEN }}
          coverage-reports: ${{ env.COVERAGE_XML_REPORT_PATH }}

  publish-package-as-artifact:
    needs: [test-and-cover-pack]
    runs-on: ubuntu-latest
    steps:
      - name: "Check repo"
        uses: actions/checkout@v3
      - name: "Publish as artifact"
        uses: actions/upload-artifact@v3
        with:
          name: "Making package"
          path: "Lib"
